name: docker-build-and-push

inputs:
  service:
    required: true
    type: string
  image-tag:
    required: true
    type: string
  dockerfilepath:
    required: false
    type: string
    default: "./Dockerfile" # Dockerfile in the root of the repo
  docker-build-args:
    required: false
    type: string
    description: "newline separated list of non-secret arguments to pass to the docker build, e.g. 'APP_ENV=stg\nFOO=foo'"
  ecr-image-path:
    required: false
    description: "custom path to access the ECR docker image"
    type: string
  FC_CICD_RW_USER_PAT:
    required: false
    description: "Personal Access Token for the fc-cicd-rw user (intent: pull private repos in the build process)"
    type: string
  PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD:
    required: true
    type: string
  JFROG_FLOWCODE_FC_PYPI_USERNAME:
    required: false
    type: string
  JFROG_FLOWCODE_FC_PYPI_PASSWORD:
    required: false
    type: string
  ECR_FLOWCODE_FC_DOCKER_SERVER:
    required: true
    type: string
  BUF_CICD_USER:
    required: false
    type: string
  BUF_CICD_TOKEN:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        file: ${{ inputs.dockerfilepath }}
        github-token: ${{ inputs.PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ${{ inputs.ECR_FLOWCODE_FC_DOCKER_SERVER }}/${{ inputs.service }}:${{ inputs.ecr-image-path }}${{ inputs.image-tag }}
        # GITHUB_USERNAME and GITHUB_PASSWORD are needed to pull private repos in the build process.
        build-args: |
          GITHUB_USERNAME=fc-cicd-rw
          PAT=${{ inputs.FC_CICD_RW_USER_PAT }}
          JFROG_FLOWCODE_FC_PYPI_USERNAME=${{ inputs.JFROG_FLOWCODE_FC_PYPI_USERNAME }}
          JFROG_FLOWCODE_FC_PYPI_PASSWORD=${{ inputs.JFROG_FLOWCODE_FC_PYPI_PASSWORD }}
          BUILD_ID=${{ github.sha }}
          VERSION=${{ github.sha }}
          ${{ inputs.docker-build-args }}
        secrets: |
          GITHUB_TOKEN=${{ inputs.PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD }}
          BUF_USER=${{ inputs.BUF_CICD_USER }}
          BUF_TOKEN=${{ inputs.BUF_CICD_TOKEN }}
