name: docker-build-and-push

inputs:
  service:
    required: true
    type: string
  image-tag:
    required: true
    type: string
  dockerfilepath:
    required: false
    type: string
    default: "./Dockerfile" # Dockerfile in the root of the repo
  docker-build-args:
    required: false
    type: string
    description: "newline separated list of non-secret arguments to pass to the docker build, e.g. 'APP_ENV=stg\nFOO=foo'"
  ecr-image-path:
    required: false
    description: "custom path to access the ECR docker image"
    type: string
  PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD:
    required: true
    type: string
  ECR_FLOWCODE_FC_DOCKER_SERVER:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        file: ${{ inputs.dockerfilepath }}
        github-token: ${{ inputs.PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ${{ inputs.ECR_FLOWCODE_FC_DOCKER_SERVER }}/${{ inputs.service }}:${{ inputs.ecr-image-path }}${{ inputs.image-tag }}
        # GITHUB_USERNAME and GITHUB_PASSWORD are needed to pull private repos in the build process.
        build-args: |
          ${{ inputs.docker-build-args }}
        secrets: |
          GITHUB_TOKEN=${{ inputs.PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD }}
