name: setup-docker

runs:
  using: "composite"
  steps:
    - name: Set up Docker Context for Buildx
      id: buildx-context
      shell: bash
      run: |
        docker context create builders
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        endpoint: builders
