name: setup-image-repository

inputs:
  service:
    required: true
    type: string
  ECR_FLOWCODE_FC_DOCKER_SERVER:
    required: true
    type: string
  ECR_FLOWCODE_FC_DOCKER_KEY:
    required: true
    type: string
  ECR_FLOWCODE_FC_DOCKER_SECRET:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.ECR_FLOWCODE_FC_DOCKER_KEY }}
        aws-secret-access-key: ${{ inputs.ECR_FLOWCODE_FC_DOCKER_SECRET }}
        aws-region: us-east-1
    - name: Set up ECR repo if doesn't exist
      id: ecr-repo
      uses: int128/create-ecr-repository-action@v1
      with:
        repository: ${{ inputs.service }}
    - name: Login to ECR
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.ECR_FLOWCODE_FC_DOCKER_SERVER }}
        username: ${{ inputs.ECR_FLOWCODE_FC_DOCKER_KEY }}
        password: ${{ inputs.ECR_FLOWCODE_FC_DOCKER_SECRET }}
