name: run-postbuild-script-flow

inputs:
  service:
    required: true
    type: string
  image-tag:
    required: true
    type: string
  ecr-image-path:
    required: false
    description: "custom path to access the ECR docker image"
    type: string
  post-build-script:
    required: true
    description: "file path of a shell script to run between the build step and the release step, e.g. 'scripts/myscript.sh'"
    type: string
  post-build-script-inputs:
    required: false
    description: "json string to pass to the post-build-script"
    type: string
  PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD:
    required: true
    type: string
  STATIC_ASSETS_S3_AWS_ACCESS_KEY_ID:
    required: true
    type: string
  STATIC_ASSETS_S3_AWS_SECRET_ACCESS_KEY:
    required: true
    type: string
  ECR_FLOWCODE_FC_DOCKER_SERVER:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Unset AWS creds env vars
      shell: bash
      run: |
        echo "AWS_ACCESS_KEY_ID=" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=" >> $GITHUB_ENV
        echo "AWS_REGION=" >> $GITHUB_ENV
    - name: Checkout repo to run post-build script
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD }}
    - name: Run post-build script
      shell: bash
      env:
        # Don't edit or delete these without confirming it won't break the scripts that use them.
        ECR_FLOWCODE_FC_DOCKER_SERVER: ${{ inputs.ECR_FLOWCODE_FC_DOCKER_SERVER }}
        SERVICE_NAME: ${{ inputs.service }}
        RELEASE_TAG: ${{ inputs.image-tag }}
        ECR_IMAGE_PATH: ${{ inputs.ecr-image-path }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        POST_BUILD_SCRIPT_INPUTS: ${{ inputs.post-build-script-inputs }}
        AWS_ACCESS_KEY_ID: ${{ inputs.STATIC_ASSETS_S3_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.STATIC_ASSETS_S3_AWS_SECRET_ACCESS_KEY }}
      run: |
        ./${{ inputs.post-build-script }}
