name: build-and-push-and-nonprod-release

on:
  workflow_call:
    inputs:
      service_name:      # Example: "ithaca"
        required: true
        type: string
      team_name:         # Example: "revenue"
        required: true
        type: string
    secrets:
      JFROG_FLOWCODE_SERVER_NAME:
        required: true
      JFROG_FLOWCODE_FC_DOCKER_USERNAME:
        required: true
      JFROG_FLOWCODE_FC_DOCKER_PASSWORD:
        required: true
      JFROG_FLOWCODE_FC_DOCKER_REPO:
        required: true
      PERSONAL_ACCESS_TOKEN_REPO:
        required: true

permissions:
      id-token: write    # Required for aws role assumption
      contents: write    # This is required for actions/checkout@v1

jobs:
  cd:
    runs-on: self-hosted
    steps:
      -
        name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      -
        name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.JFROG_FLOWCODE_SERVER_NAME }}
          username: ${{ secrets.JFROG_FLOWCODE_FC_DOCKER_USERNAME }}
          password: ${{ secrets.JFROG_FLOWCODE_FC_DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN_REPO }}
          tags: |
            ${{ secrets.JFROG_FLOWCODE_SERVER_NAME }}/${{ secrets.JFROG_FLOWCODE_FC_DOCKER_REPO }}/${{ inputs.service_name }}:${{ github.run_number }}
      -
        name: Checkout sample-infra-kubernetes repo
        uses: actions/checkout@v2
        with:
          repository: dtx-company/sample-infra-kubernetes
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_REPO }}
      -
        name: Update the image tag in fc-services-dev and push a branch
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

          git config --local user.name ${{ github.event.pusher.name }}
          git config --local user.email ${{ github.event.pusher.email }}
          git checkout -b "auto/bump-${{ inputs.service_name }}-to-${{ github.run_number }}"

          filename="cloud/aws/fc-services-dev/use1/primary/${{ inputs.team_name }}/applications/${{ inputs.service_name }}/values.yaml"
          yq  -i eval '.fc-service.process.tag = "${{ github.run_number }}"' ${filename}

          git diff
          git add ${filename}
          git commit -m "auto: bump ${{ inputs.service_name }} to ${{ github.run_number }} for fc-services-dev"
          git show-ref
          git push origin HEAD
          git request-pull origin/trunk ./


