name: build-and-push-and-nonprod-release

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      project:
        required: true
        type: string
    secrets:
      JFROG_FLOWCODE_SERVER_NAME:
        required: true
      JFROG_FLOWCODE_FC_DOCKER_USERNAME:
        required: true
      JFROG_FLOWCODE_FC_DOCKER_PASSWORD:
        required: true
      JFROG_FLOWCODE_FC_DOCKER_REPO:
        required: true
      PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD:
        required: true

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      -
        name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      -
        name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.JFROG_FLOWCODE_SERVER_NAME }}
          username: ${{ secrets.JFROG_FLOWCODE_FC_DOCKER_USERNAME }}
          password: ${{ secrets.JFROG_FLOWCODE_FC_DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.JFROG_FLOWCODE_SERVER_NAME }}/${{ secrets.JFROG_FLOWCODE_FC_DOCKER_REPO }}/${{ inputs.service }}:${{ env.IMAGE_TAG }}
      -
        name: Checkout kubernetes infra repo
        uses: actions/checkout@v2
        with:
          repository: dtx-company/fc-infra-kubernetes
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD }}
      -
        name: Update the image tags in values.yaml and push commit
        run: |
          echo "Installing yq..."
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

          echo; echo;
          echo "Setting git config..."
          git config --local user.name ${{ github.event.pusher.name }}
          git config --local user.email ${{ github.event.pusher.email }}

          echo; echo;
          echo "Updating values.yaml..."
          awsenvs=( "fc-services-stg" "fc-services-preprod" )
          for awsenv in "${awsenvs[@]}"
          do
            filename="cloud/aws/${awsenv}/use1/primary/${{ inputs.project }}/applications/${{ inputs.service }}/values.yaml"
            yq -i eval '.fc-service.process.tag = ${{ env.IMAGE_TAG }}' ${filename}
            git add ${filename}
          done

          echo; echo;
          echo "Pushing to git..."
          git diff HEAD
          if [[ $(git diff HEAD) ]]; then
            git commit -m "cicd-auto: nonprod bump ${{ inputs.service }} to ${{ env.IMAGE_TAG }}" -m "triggered from https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
            git push origin HEAD
          else
            echo "Nothing to push"
          fi
