name: build-and-push

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

permissions:
      id-token: write    # Required for aws role assumption
      contents: write    # This is required for actions/checkout@v2

jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      -
        name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.JFROG_FLOWCODE_SERVER_NAME }}
          username: ${{ secrets.JFROG_FLOWCODE_FC_DOCKER_USERNAME }}
          password: ${{ secrets.JFROG_FLOWCODE_FC_DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.JFROG_FLOWCODE_SERVER_NAME }}/${{ secrets.JFROG_FLOWCODE_FC_DOCKER_REPO }}/${{ inputs.service_name }}:${{ github.run_number }}

  deploy:
    runs-on: self-hosted
    steps:
      -
        name: Checkout sample-infra-kubernetes repo
        uses: actions/checkout@v2
        with:
          repository: dtx-company/sample-infra-kubernetes
      -
        name: Update image tag
        run: |
          git config --local user.email
          git config --local user.name
          git commit -m "auto: bump ${{ inputs.service-name }} to ${{ github.run_number }} for fc-services-dev, fc-services-stg, fc-services-preprod"

