name: build-and-tag-and-prod-release

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      project:
        required: true
        type: string
      extra-deployments:
        required: false
        description: "for services that have multiple deployments in their values.yaml in fc-infra-kubernetes, provide the names of the other deployments e.g. 'worker,beat' as a comma separated list"
        type: string
      dockerfilepath:
        required: false
        type: string
        default: "./Dockerfile" # Dockerfile in the root of the repo
    secrets:
      JFROG_FLOWCODE_SERVER_NAME:
        required: true
      JFROG_FLOWCODE_FC_DOCKER_USERNAME:
        required: true
      JFROG_FLOWCODE_FC_DOCKER_PASSWORD:
        required: true
      JFROG_FLOWCODE_FC_DOCKER_REPO:
        required: true
      PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD:
        required: true

jobs:
  release:
    runs-on: self-hosted
    steps:
      -
        # Checkout is required for publish_release step below to work.
        name: Checkout service repository
        uses: actions/checkout@v2
      -
        name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      -
        name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.JFROG_FLOWCODE_SERVER_NAME }}
          username: ${{ secrets.JFROG_FLOWCODE_FC_DOCKER_USERNAME }}
          password: ${{ secrets.JFROG_FLOWCODE_FC_DOCKER_PASSWORD }}
      -
        # Node is required -- is it already provided on our machines or is it necessary to set it up as a step?
        name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      -
        # This step does the github release and github tag.
        # It also outputs the tag so that subsequent steps can use it.
        name: Create Github Release and Notes
        id: publish_release
        run: |
          GITHUB_TOKEN=${{ github.token }} npx semantic-release@19
          echo ::set-output name=release_tag::$(git tag --sort committerdate | tail -1)
      -
        # Same as the nonprod workflow, except the image tag is the github release tag not the SHA.
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ inputs.dockerfilepath }}
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.JFROG_FLOWCODE_SERVER_NAME }}/${{ secrets.JFROG_FLOWCODE_FC_DOCKER_REPO }}/${{ inputs.service }}:${{ steps.publish_release.outputs.release_tag }}
          # GITHUB_USERNAME and GITHUB_PASSWORD are needed to pull private repos in the build process.
          build-args: |
            GITHUB_USERNAME=fc-cicd-rw
          secrets: |
            GITHUB_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD }}
      -
        name: Checkout kubernetes infra repo
        uses: actions/checkout@v2
        with:
          repository: dtx-company/fc-infra-kubernetes
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD }}
      -
        # This is heavily duplicated with the nonprod workflow but it cannot be factored out
        # and reused because a reusable workflow cannot call another reusable workflow according to the docs:
        # https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows#limitations
        name: Update the image tags in values.yaml and push commit
        run: |
          echo "Installing yq..."
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

          echo;
          echo "Setting git config..."
          git config --local user.name "${{ github.event.sender.login }}"
          git config --local user.email "${{ github.event.sender.id }}+${{ github.event.sender.login }}@users.noreply.github.com"

          echo;
          awsenvs=( "fc-services-prod" )
          for awsenv in "${awsenvs[@]}"
          do
            filename="cloud/aws/${awsenv}/use1/primary/${{ inputs.project }}/applications/${{ inputs.service }}/values.yaml"
            IFS=, read -ra deployments <<< "${{ inputs.extra-deployments }}"  # split by comma into an array
            deployments+=("fc-service")                                       # fc-service is always included
            echo "Updating ${filename} for deployments ${deployments[*]}..."
            for d in "${deployments[@]}"
            do
              path=".${d}.process.tag" yq -i eval 'eval(strenv(path)) = "${{ steps.publish_release.outputs.release_tag }}"'  ${filename}
            done
            git add ${filename}
          done

          echo; echo;
          echo "Pushing to git..."
          git diff HEAD
          if [[ $(git diff HEAD) ]]; then
            git commit -m "cicd-auto: prod bump ${{ inputs.service }} to ${{ steps.publish_release.outputs.release_tag }}" -m "triggered from https://github.com/${{ github.repository }}/releases/tag/${{ steps.publish_release.outputs.release_tag }}"
            git push origin HEAD
          else
            echo "Nothing to push"
          fi
