name: build-and-push-and-nonprod-release

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      project:
        required: true
        type: string
    secrets:
      JFROG_FLOWCODE_SERVER_NAME:
        required: true
      JFROG_FLOWCODE_FC_DOCKER_USERNAME:
        required: true
      JFROG_FLOWCODE_FC_DOCKER_PASSWORD:
        required: true
      JFROG_FLOWCODE_FC_DOCKER_REPO:
        required: true
      PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD:
        required: true

permissions:
      id-token: write    # Required for aws role assumption
      contents: write    # This is required for actions/checkout@v1

jobs:
  cd:
    runs-on: self-hosted
    env:
      IMAGE_TAG: ${{ github.run_number }}
    steps:
      -
        name: "Check IMAGE_TAG"
        run: "echo ${{ env.IMAGE_TAG }}"
      -
        name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      -
        name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.JFROG_FLOWCODE_SERVER_NAME }}
          username: ${{ secrets.JFROG_FLOWCODE_FC_DOCKER_USERNAME }}
          password: ${{ secrets.JFROG_FLOWCODE_FC_DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD }}
          tags: |
            ${{ secrets.JFROG_FLOWCODE_SERVER_NAME }}/${{ secrets.JFROG_FLOWCODE_FC_DOCKER_REPO }}/${{ inputs.service }}:${{ env.IMAGE_TAG }}
      -
        name: Checkout sample-infra-kubernetes repo
        uses: actions/checkout@v2
        with:
          repository: dtx-company/sample-infra-kubernetes
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB_WORKFLOWS_CICD }}
      -
        name: Install yq
        uses: chrisdickinson/setup-yq@latest
      -
        name: Update the image tag in fc-services-dev and push a branch
        run: |
          git config --local user.name ${{ github.event.pusher.name }}
          git config --local user.email ${{ github.event.pusher.email }}
          git checkout -b "auto/bump-${{ inputs.service }}-to-${{ env.IMAGE_TAG }}"

          filename="cloud/aws/fc-services-dev/use1/primary/${{ inputs.project }}/applications/${{ inputs.service }}/values.yaml"
          yq  -i eval '.fc-service.process.tag = ${{ env.IMAGE_TAG }}' ${filename}

          git diff
          git add ${filename}
          git commit -m "cicd-auto: nonprod bump ${{ inputs.service }} to ${{ env.IMAGE_TAG }}"
          git show-ref
          git push origin HEAD
          git request-pull origin/trunk ./


