name: conventional-pr-title

on:
  workflow_call:

jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        with:
          # Configuration docs: https://github.com/marketplace/actions/semantic-pull-request#configuration
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
