name: conventional-pr-title

on:
  workflow_call:

jobs:
  validate:
    name: validate-pr-title
    runs-on: self-hosted
    steps:
      # Configuration docs: https://github.com/marketplace/actions/semantic-pull-request#configuration
      # We allow types based on conventionalcommit standard: https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-conventionalcommits/writer-opts.js#L179-L192
      - uses: amannn/action-semantic-pull-request@v4
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            feature
            fix
            perf
            refactor
            revert
            style
            test
        env:
          # GITHUB_TOKEN is available automatically.
          # See https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/#:~:text=GitHub%20Actions%20now%20lets%20you,token%20when%20a%20job%20completes.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
