name: conventional-pr-title

on:
  workflow_call:

jobs:
  validate:
    name: validate-pr-title
    runs-on: [self-hosted, fc-general]
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
