name: release-notes

on:
  workflow_call:

jobs:
  release:
    runs-on: self-hosted
    steps:
      -
        # Checkout is required for publish_release step below to work.
        name: Checkout service repository
        uses: actions/checkout@v3
      -
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      -
        name: Create Github Release
        run: |
          npm i -g @flowcode/semantic-release-fc-shared-config
          GITHUB_TOKEN=${{ github.token }} npx semantic-release@19 -e $(npm root -g)/@flowcode/semantic-release-fc-shared-config