name: tf-module-tag-and-release

on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: "self-hosted"
        description: "the github runner to run on, options are {ubuntu-latest, self-hosted, frontend}"

jobs:
  release:
    runs-on: ${{ inputs.runner }}
    steps:
      -
        # Checkout is required for publish_release step below to work.
        name: Checkout service repository
        uses: actions/checkout@v3
      -
        # Node is required -- is it already provided on our machines or is it necessary to set it up as a step?
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      -
        # This step does the github release and github tag.
        # It also outputs the tag so that subsequent steps can use it.
        name: Create Github Release and Notes
        id: publish_release
        run: |
          npm i -g @flowcode/semantic-release-fc-shared-config
          GITHUB_TOKEN=${{ github.token }} npx semantic-release@19 -e $(npm root -g)/@flowcode/semantic-release-fc-shared-config
          echo ::set-output name=release_tag::$(git tag --sort committerdate | tail -1)
